In [156]:
#Libraries 
import pandas as pd
from math import sqrt
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [157]:
#Reading CSV Files
hap_15 = pd.read_csv("2015.csv")
hap_16 = pd.read_csv("2016.csv")
hap_17 = pd.read_csv("2017.csv")

In [158]:
#Data Preperation
hap_15.columns
columns_2015 = ['Region', 'Standard Error',]
new_2015 = hap_15.drop(columns_2015, axis=1)
sort0_2015 = new_2015.sort_values(by=['Country'])
Column = ['Country','Happiness Rank']
sort_2015 = sort0_2015.drop(Column, axis=1)
sort_2015.head()

,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
142,3.575,0.31982,0.30285,0.30335,0.23414,0.09719,0.36510,1.95210
90,4.959,0.87867,0.80434,0.81325,0.35733,0.06413,0.14272,1.89894
65,5.605,0.93929,1.07772,0.61766,0.28579,0.17383,0.07822,2.43209
128,4.033,0.75778,0.86040,0.16683,0.10384,0.07122,0.12344,1.94939
28,6.574,1.05351,1.24823,0.78723,0.44974,0.08484,0.11451,2.83600

In [159]:
hap_16.columns
columns_2016 = ['Region', 'Lower Confidence Interval','Upper Confidence Interval' ]
new_2016 = hap_16.drop(columns_2016, axis=1)
sort0_2016 = new_2016.sort_values(by=['Country'])
Column = ['Country','Happiness Rank']
sort_2016 = sort0_2016.drop(Column, axis=1)
sort_2016.head()

,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
144,3.360,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
102,4.655,0.95530,0.50163,0.73007,0.31866,0.05301,0.16840,1.92816
36,6.355,1.05266,0.83309,0.61804,0.21006,0.16157,0.07044,3.40904
132,3.866,0.84731,0.66366,0.04991,0.00589,0.08434,0.12071,2.09459
24,6.650,1.15137,1.06612,0.69711,0.42284,0.07296,0.10989,3.12985

In [160]:
hap_17.columns
columns_2017 = ['Whisker.high','Whisker.low' ]
new_2017 = hap_17.drop(columns_2017, axis=1)
sort0_2017 = new_2017.sort_values(by=['Country'])
Column = ['Country','Happiness Rank']
sort_2017 = sort0_2017.drop(Column, axis=1)
sort_2017.head()

,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual
134,3.794,0.401477,0.581543,0.180747,0.106180,0.311871,0.061158,2.150801
106,4.644,0.996193,0.803685,0.731160,0.381499,0.201313,0.039864,1.490442
51,5.872,1.091864,1.146217,0.617585,0.233336,0.069437,0.146096,2.567604
133,3.795,0.858428,1.104412,0.049869,0.000000,0.097926,0.069720,1.614482
23,6.599,1.185295,1.440451,0.695137,0.494519,0.109457,0.059740,2.614005

In [161]:
print(sort_2015.isnull().any())
print(sort_2016.isnull().any())
print(sort_2017.isnull().any())

Happiness Score                  False
Economy (GDP per Capita)         False
Family                           False
Health (Life Expectancy)         False
Freedom                          False
Trust (Government Corruption)    False
Generosity                       False
Dystopia Residual                False
dtype: bool
Happiness Score                  False
Economy (GDP per Capita)         False
Family                           False
Health (Life Expectancy)         False
Freedom                          False
Trust (Government Corruption)    False
Generosity                       False
Dystopia Residual                False
dtype: bool
Happiness Score                  False
Economy (GDP per Capita)         False
Family                           False
Health (Life Expectancy)         False
Freedom                          False
Generosity                       False
Trust (Government Corruption)    False
Dystopia Residual                False
dtype: bool

In [162]:
#I noticed some countries are not in the all of the years. So, i removed the rows from csv file by excel. 
#Now, each csv file containes 148 entries and 8 column

In [163]:
sort_2015.info()
sort_2016.info()
sort_2017.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 148 entries, 142 to 107
Data columns (total 8 columns):
Happiness Score                  148 non-null float64
Economy (GDP per Capita)         148 non-null float64
Family                           148 non-null float64
Health (Life Expectancy)         148 non-null float64
Freedom                          148 non-null float64
Trust (Government Corruption)    148 non-null float64
Generosity                       148 non-null float64
Dystopia Residual                148 non-null float64
dtypes: float64(8)
memory usage: 10.4 KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 148 entries, 144 to 123
Data columns (total 8 columns):
Happiness Score                  148 non-null float64
Economy (GDP per Capita)         148 non-null float64
Family                           148 non-null float64
Health (Life Expectancy)         148 non-null float64
Freedom                          148 non-null float64
Trust (Government Corruption)    148 non-null float64
Generosity                       148 non-null float64
Dystopia Residual                148 non-null float64
dtypes: float64(8)
memory usage: 10.4 KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 148 entries, 134 to 132
Data columns (total 8 columns):
Happiness Score                  148 non-null float64
Economy (GDP per Capita)         148 non-null float64
Family                           148 non-null float64
Health (Life Expectancy)         148 non-null float64
Freedom                          148 non-null float64
Generosity                       148 non-null float64
Trust (Government Corruption)    148 non-null float64
Dystopia Residual                148 non-null float64
dtypes: float64(8)
memory usage: 10.4 KB

In [164]:
mse = mean_absolute_error(sort_2016,sort_2015)
print('Mean Absolute Error:', mse)

Mean Absolute Error: 0.11371956925675678

In [165]:
mse = mean_absolute_error(sort_2017,sort_2016)
print('Mean Absolute Error:', mse)

Mean Absolute Error: 0.18221752275516215

In [166]:
mse = mean_absolute_error(sort_2017,sort_2015)
print('Mean Absolute Error:', mse)

Mean Absolute Error: 0.17667612606146815

In [167]:
frames = [sort_2015, sort_2016, sort_2017]
happiness = pd.concat(frames)
happiness.describe()

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,Dystopia Residual,Economy (GDP per Capita),Family,Freedom,Generosity,Happiness Score,Health (Life Expectancy),Trust (Government Corruption)
count,444.000000,444.000000,444.000000,444.000000,444.000000,444.000000,444.000000,444.000000
mean,2.073015,0.950083,1.003009,0.401457,0.242039,5.397698,0.595709,0.132379
std,0.559464,0.405180,0.313089,0.150071,0.132646,1.138309,0.231993,0.111604
min,0.328580,0.000000,0.000000,0.000000,0.000000,2.839000,0.000000,0.000000
25%,1.726444,0.647590,0.811422,0.295713,0.149619,4.512750,0.440428,0.058570
50%,2.083533,1.015730,1.034090,0.415895,0.223870,5.319000,0.638287,0.094455
75%,2.444082,1.272072,1.239170,0.514542,0.316964,6.299000,0.787435,0.171712
max,3.602140,1.870766,1.610574,0.669730,0.838075,7.587000,1.025250,0.551910

In [168]:
columns_2 = ['Happiness Score', 'Family','Freedom','Generosity', 'Dystopia Residual']
temp_dataframe = sort_2016.drop(columns_2, axis=1)
X = temp_dataframe
X.head()

,Economy (GDP per Capita),Health (Life Expectancy),Trust (Government Corruption)
144,0.38227,0.17344,0.07112
102,0.95530,0.73007,0.05301
36,1.05266,0.61804,0.16157
132,0.84731,0.04991,0.08434
24,1.15137,0.69711,0.07296

In [169]:
label='Happiness Score'
y = hap_16[label]

regressor = LinearRegression()
model = regressor.fit(X,y)
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [170]:
new_features = ['Trust (Government Corruption)','Health (Life Expectancy)','Economy (GDP per Capita)']
train_x = sort0_2017[new_features]
train_y = sort0_2017[label]
prediction = regressor.predict(train_x)

In [171]:
temp_df = pd.DataFrame()
temp_df['Original Happiness Score'] = train_y
temp_df['Predicted 2018 Happiness Score'] = prediction 
temp_df.head()

     Original Happiness Score  Predicted 2018 Happiness Score
134                     3.794                        5.198511
106                     4.644                        4.850852
51                      5.872                        4.777943
133                     3.795                        4.888381
23                      6.599                        4.723699

In [172]:
temp_df['Country'] = sort0_2017['Country']

In [176]:
mse = mean_absolute_error(sort0_2017[label],prediction)
mean_squared_error_value = sqrt(mean_squared_error(y_true=train_y,y_pred=prediction))
print('Mean Squared Error Value:', mean_squared_error_value)
print('Mean Absolute Error:', mse)

Mean Squared Error Value: 1.4459898911608933
Mean Absolute Error: 1.2076840546364256